name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Navigate to workflow directory
        run: cd .github/workflows
      - name: make
        run: |
          cd .github/workflows
          make
      - name: make check
        run: |
          cd .github/workflows
          make check
      - name: make distcheck
        run: |
          cd .github/workflows
          make distcheck
