name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: make
        run: make
        working-directory: .github/workflows
      - name: make check
        run: make check
        working-directory: .github/workflows
      - name: make distcheck
        run: make distcheck
        working-directory: .github/workflows
