name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Verify Makefile
        run: |
          if [ ! -f Makefile ]; then
            echo "Makefile not found. Please add a Makefile.";
            exit 1;
          fi
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
